# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Onur Akpolat
tagline:          thinking loud.
url:              http://blog.onurakpolat.com
paginate:         1
baseurl:          /
author:
  name:           Onur Akpolat
  url:            https://twitter.com/onurakpolat
  email:          onur.akpolat@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
  
# Custom pages
pages_list:       
  About: '/about'
  Archive: '/archive'

# Allow URL Redirects: 
#  * https://help.github.com/articles/redirects-on-github-pages
gems:
  - jekyll-redirect-from